<x-layouts.dashboard :title="$transaction->exists ? 'Edit Transaction' : 'Create Transaction'" eyebrow="Transactions">
    <section class="max-w-3xl rounded-[2rem] border border-white/70 bg-white/75 p-5 shadow-xl shadow-slate-200/50 backdrop-blur-2xl dark:border-white/10 dark:bg-white/[0.04]">
        @include('dashboard.partials.flash')
        <form method="POST" action="{{ $transaction->exists ? route('dashboard.transactions.update', $transaction) : route('dashboard.transactions.store') }}" class="space-y-4">
            @csrf
            @if($transaction->exists) @method('PUT') @endif
            <div><label class="text-sm font-bold">Description</label><input name="description" value="{{ old('description', $transaction->description) }}" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"></div>
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-bold">Amount</label><input name="amount" type="number" step="0.01" value="{{ old('amount', $transaction->amount) }}" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"></div><div><label class="text-sm font-bold">Type</label><select name="type" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10">@foreach(\App\Enums\TransactionType::cases() as $type)<option value="{{ $type->value }}" @selected(old('type', $transaction->type?->value) === $type->value)>{{ $type->value }}</option>@endforeach</select></div></div>
            <div><label class="text-sm font-bold">Category</label><select name="category_id" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $transaction->category_id) === (string) $category->id)>{{ $category->type->value }} · {{ $category->name }}</option>@endforeach</select></div>
            <div class="grid gap-4 sm:grid-cols-3"><div><label class="text-sm font-bold">Date</label><input name="transaction_date" type="date" value="{{ old('transaction_date', optional($transaction->transaction_date)->format('Y-m-d') ?? now()->toDateString()) }}" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"></div><div><label class="text-sm font-bold">Time</label><input name="transaction_time" type="time" value="{{ old('transaction_time', $transaction->transaction_time ? \Illuminate\Support\Carbon::parse($transaction->transaction_time)->format('H:i') : '') }}" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"></div><div><label class="text-sm font-bold">Currency</label><input name="currency" value="{{ old('currency', $transaction->currency ?? 'IDR') }}" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10"></div></div>
            <div><label class="text-sm font-bold">Notes</label><textarea name="notes" rows="4" class="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/10">{{ old('notes', $transaction->notes) }}</textarea></div>
            <div class="flex gap-3"><button class="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white dark:bg-white dark:text-slate-950">Save</button><a href="{{ route('dashboard.transactions') }}" class="rounded-2xl bg-slate-100 px-5 py-3 text-sm font-black dark:bg-white/10">Cancel</a></div>
        </form>
    </section>
</x-layouts.dashboard>
