<x-layouts.dashboard :title="$category->exists ? 'Edit Category' : 'Create Category'" eyebrow="Categories">
<section class="max-w-2xl rounded-[2rem] border border-white/70 bg-white/75 p-5 dark:border-white/10 dark:bg-white/[0.04]">@include('dashboard.partials.flash')<form method="POST" action="{{ $category->exists ? route('dashboard.categories.update', $category) : route('dashboard.categories.store') }}" class="space-y-4">@csrf @if($category->exists) @method('PUT') @endif
<div><label class="text-sm font-bold">Name</label><input name="name" value="{{ old('name', $category->name) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div>
<div><label class="text-sm font-bold">Slug</label><input name="slug" value="{{ old('slug', $category->slug) }}" placeholder="auto-generated if empty" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-bold">Type</label><select name="type" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10">@foreach(\App\Enums\TransactionType::cases() as $type)<option value="{{ $type->value }}" @selected(old('type', $category->type?->value) === $type->value)>{{ $type->value }}</option>@endforeach</select></div><div><label class="text-sm font-bold">Sort</label><input name="sort_order" type="number" value="{{ old('sort_order', $category->sort_order ?? 0) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-bold">Icon</label><input name="icon" value="{{ old('icon', $category->icon) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div><div><label class="text-sm font-bold">Color</label><input name="color" value="{{ old('color', $category->color ?? '#64748b') }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div></div>
<label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $category->is_active ?? true))> Active</label>
<div class="flex gap-3"><button class="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white dark:bg-white dark:text-slate-950">Save</button><a href="{{ route('dashboard.categories') }}" class="rounded-2xl bg-slate-100 px-5 py-3 text-sm font-black dark:bg-white/10">Cancel</a></div>
</form></section>
</x-layouts.dashboard>
