<x-layouts.dashboard :title="$budget->exists ? 'Edit Budget' : 'Create Budget'" eyebrow="Budgets">
<section class="max-w-2xl rounded-[2rem] border border-white/70 bg-white/75 p-5 dark:border-white/10 dark:bg-white/[0.04]">@include('dashboard.partials.flash')
<form method="POST" action="{{ $budget->exists ? route('dashboard.budgets.update', $budget) : route('dashboard.budgets.store') }}" class="space-y-4">@csrf @if($budget->exists) @method('PUT') @endif
<div><label class="text-sm font-bold">Category</label><select name="category_id" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"><option value="">Total Budget</option>@foreach($expenseCategories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id', $budget->category_id)===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-bold">Year</label><input name="year" type="number" value="{{ old('year', $budget->year ?? now()->year) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div><div><label class="text-sm font-bold">Month</label><input name="month" type="number" min="1" max="12" value="{{ old('month', $budget->month ?? now()->month) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div></div>
<div><label class="text-sm font-bold">Amount</label><input name="amount" type="number" step="1000" value="{{ old('amount', $budget->amount) }}" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10"></div><input type="hidden" name="currency" value="IDR">
<div><label class="text-sm font-bold">Notes</label><textarea name="notes" rows="4" class="mt-2 w-full rounded-2xl border px-4 py-3 dark:bg-white/10">{{ old('notes', $budget->notes) }}</textarea></div>
<div class="flex gap-3"><button class="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white dark:bg-white dark:text-slate-950">Save</button><a href="{{ route('dashboard.budget') }}" class="rounded-2xl bg-slate-100 px-5 py-3 text-sm font-black dark:bg-white/10">Cancel</a></div>
</form></section></x-layouts.dashboard>
